### PR TITLE
Migrating oxMemcached to use memcached instead of memcache

### PR DESCRIPTION
**Pull request by sgreiner**
Memcache is not available for PHP 7, we can only use the newer Memcached extension.

### CODE REVIEW

**Comment by mbeccati** [comment]
A couple of questions:
* is their API perfectlyidentical?
* why not allowing memcached as a fallback (or vice-versa), so that both extensions are supported?

**Comment by sgreiner** [comment]
I only checked the addServer Method, the APIs are not identical, but as revive uses them, they are.
But the set and replace methods don't have a compress parameter any more.
I will fix that and I try to implement Memcache as fallback.

**Comment by sgreiner** [comment]
Its implemented now.

**Comment by mbeccati** [comment]
Could you please fix the code style to adhere to PSR-2 and fixup/squash the commits into one? Thanks.

**Pull request merged**
