### PR TITLE
Badlogin in support for fail2ban: preventing brute force

### PR DESCRIPTION
**Pull request by lcuis**
~~In `constants.php` , set `$GLOBALS['badLoginLogFilePath']` to the path of the log file fail2ban can use to ban an IP trying to brute force your site. For example `/var/log/reviveBadLogin.log` .~~ Edit 2022-08-04: this was replaced by a UI conf parameter; see https://github.com/revive-adserver/revive-adserver/pull/1389#issuecomment-1205826049

Run the following commands to make the file writable:
```shell
$ touch /var/log/reviveBadLogin.log
$ chown www-data:www-data /var/log/reviveBadLogin.log
```

Add the following in the `/etc/fail2ban/filter.d/revive.conf` file:
```
[Definition]
failregex = ^.*: <HOST>$
datepattern = {^LN-BEG}Epoch
```

Add the following in the `/etc/fail2ban/filter.d/revive.conf` file:
```
[revive]
enabled = true
port = 80,443
protocol = tcp
filter = revive
maxretry = 3
bantime = 86400
findtime = 43200
logpath = /var/log/reviveBadLogin.log
```

Restart fail2ban with the following command:
```shell
$ systemctl restart fail2ban
```

I was able to test this with a VPN. I entered 3 times bad credentials and my IP got banned.

It is likely that call to `badLogin.php` would be desirable from other places susceptible to be used for brute forcing.

### CODE REVIEW

**Comment by mbeccati** [comment]
Thanks you very much your pull request!

It seems to be an interesting feature, we will discuss if and how we can make it fit in the roadmap. The code style however doesn't seem to fit the rest of the project, so we will have some work to do there.

**Comment by erikgeurts** [comment]
Indeed, interesting! However, it does seem to rely on an external service/tool that may not be available to all/in all hosting environments, so it should be optional with default "off".

**Comment by lcuis** [comment]
Thank you very much @mbeccati and @erikgeurts for your very positive and fast answers!

I would be happy to improve the style if you have some guidelines or examples you'd like me to follow.

I fully agree on the fact it should be turned "off" by default. It is too specific to the user installation to be easily generalized.

**Comment by lcuis** [comment]
I just realized that there is a UI configuration section where the bad login log path parameter would be quite welcome.
I'm trying to fit this in.

**Comment by lcuis** [comment]
I added the string `strGuiBadLoginLogPath` to the `lib/max/language/en/settings.lang.php` file. I see that Crowdin is in use. I am not familiar with it. Is there something I should do for the translations of this string?

**Comment by lcuis** [comment]
I was able to get my bad login log path parameter in the UI conf as shown here:
image

It is disabled (empty) by default.

I get this in the `/var/log/reviveBadLogin.log` file after three bad logins:
```
1659650809: MY_VPN_IP
1659651450: MY_VPN_IP
1659651459: MY_VPN_IP
```

I also get this in the `/var/log/fail2ban.log` file:
```
2022-08-05 00:06:50,730 fail2ban.filter         [1747169]: INFO    [revive] Found MY_VPN_IP - 2022-08-05 00:06:49
2022-08-05 00:17:32,835 fail2ban.filter         [1747169]: INFO    [revive] Found MY_VPN_IP - 2022-08-05 00:17:30
2022-08-05 00:17:40,045 fail2ban.filter         [1747169]: INFO    [revive] Found MY_VPN_IP - 2022-08-05 00:17:39
2022-08-05 00:17:40,266 fail2ban.actions        [1747169]: NOTICE  [revive] Ban MY_VPN_IP
```

**Comment by lcuis** [comment]
I just noticed this very interesting documentation section:
https://documentation.revive-adserver.com/display/DOCS/Before+you+Start
I may still have a few things to adapt.

**Comment by lcuis** [comment]
Here is how I ran the unit and integration tests against my proposed PR:
```
cd /var/www/html/
git clone https://github.com/lcuis/revive-adserver.git revive-adserver-badLogin
cd revive-adserver-badLogin/
git fetch origin badlogin:badlogin
git switch badlogin
cp etc/test.conf.php var/test.conf.php
```
Edited to set the SQL username and password:
```
nano var/test.conf.php
```

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
chown -R www-data:www-data .
sudo -u www-data php composer.phar install
cd tests
sudo -u www-data /usr/bin/php run.php --type=unit --level=file --layer=db --folder=lib/util/file --file=badLogin.util.test.php --format=text --host=test
```
Gave this:
```
UNIT: Database Abstraction Layer (DB): lib/util/file/badLogin.util.test.php
OK
Test cases run: 1/1, Passes: 1, Failures: 0, Exceptions: 0
```

```
sudo -u www-data /usr/bin/php -q cli_test_runner.php /usr/bin/php unit>unit_test_results.xml
grep Failures unit_test_results.xml|grep -v "Failures: 0,"
```
Gave this:
```
Test cases run: 1/1, Passes: 12, Failures: 1, Exceptions: 0</fail>
Test cases run: 1/1, Passes: 94, Failures: 1, Exceptions: 0</fail>
```
Here are the details of those two failures in `unit_test_results.xml`:
```
...
          <case>
            <name>File Charset.db.test.php (unit)</name>
            <test>
              <name>lib/OA/DB/tests/unit/Charset.db.test.php</name>
              <fail>Directory: /var/www/html/revive-adserver-badLogin/tests
Failed command: /usr/bin/php run.php --type=unit --level=file --layer=db --folder=lib/OA/DB --file=Charset.db.test.php --format=text --host=test 2&gt;&amp;1
Charset.db.test.php
UNIT: Database Abstraction Layer (DB): lib/OA/DB/Charset.db.test.php
1) Equal expectation fails at character 4 with [utf8mb3] and [utf8] at [/var/www/html/revive-adserver-badLogin/lib/OA/DB/tests/unit/Charset.db.test.php line 63]
        in testMySQL
        in Test_OA_DB_Charset
        in /var/www/html/revive-adserver-badLogin/lib/OA/DB/tests/unit/Charset.db.test.php
FAILURES!!!
Test cases run: 1/1, Passes: 12, Failures: 1, Exceptions: 0</fail>
              <time>0.22428488731384</time>
            </test>
          </case>
...
          <case>
            <name>File UpgradeConfig.up.test.php (unit)</name>
            <test>
              <name>lib/OA/Upgrade/tests/unit/UpgradeConfig.up.test.php</name>
              <fail>Directory: /var/www/html/revive-adserver-badLogin/tests
Failed command: /usr/bin/php run.php --type=unit --level=file --layer=up --folder=lib/OA/Upgrade --file=UpgradeConfig.up.test.php --format=text --host=test 2&gt;&amp;1
UpgradeConfig.up.test.php
UNIT: Upgrade Classes: lib/OA/Upgrade/UpgradeConfig.up.test.php
1) New config items have NOT been added to working test.conf.php at [/var/www/html/revive-adserver-badLogin/lib/OA/Upgrade/tests/unit/UpgradeConfig.up.test.php line 283]
        in test_checkForConfigAdditions
        in Test_OA_Upgrade_Config
        in /var/www/html/revive-adserver-badLogin/lib/OA/Upgrade/tests/unit/UpgradeConfig.up.test.php
FAILURES!!!
Test cases run: 1/1, Passes: 94, Failures: 1, Exceptions: 0</fail>
              <time>66.296101093292</time>
            </test>
          </case>
...
```
I ran the integration tests:
```
sudo -u www-data /usr/bin/php -q cli_test_runner.php /usr/bin/php integration>integration_test_results.xml
grep Failures unit_test_results.xml|grep -v "Failures: 0,"
```
Which gave this:
```
Test cases run: 1/1, Passes: 12, Failures: 1, Exceptions: 0</fail>
Test cases run: 1/1, Passes: 94, Failures: 1, Exceptions: 0</fail>
```
With details from `integration_test_results.xml`:
```
...
          <case>
            <name>File Charset.db.test.php (integration)</name>
            <test>
              <name>lib/OA/DB/tests/unit/Charset.db.test.php</name>
              <fail>Directory: /var/www/html/revive-adserver-badLogin/tests
Failed command: /usr/bin/php run.php --type=unit --level=file --layer=db --folder=lib/OA/DB --file=Charset.db.test.php --format=text --host=test 2&gt;&amp;1
Charset.db.test.php
UNIT: Database Abstraction Layer (DB): lib/OA/DB/Charset.db.test.php
1) Equal expectation fails at character 4 with [utf8mb3] and [utf8] at [/var/www/html/revive-adserver-badLogin/lib/OA/DB/tests/unit/Charset.db.test.php line 63]
        in testMySQL
        in Test_OA_DB_Charset
        in /var/www/html/revive-adserver-badLogin/lib/OA/DB/tests/unit/Charset.db.test.php
FAILURES!!!
Test cases run: 1/1, Passes: 12, Failures: 1, Exceptions: 0</fail>
              <time>0.26258397102356</time>
            </test>
          </case>
...
          <case>
            <name>File UpgradeConfig.up.test.php (integration)</name>
            <test>
              <name>lib/OA/Upgrade/tests/unit/UpgradeConfig.up.test.php</name>
              <fail>Directory: /var/www/html/revive-adserver-badLogin/tests
Failed command: /usr/bin/php run.php --type=unit --level=file --layer=up --folder=lib/OA/Upgrade --file=UpgradeConfig.up.test.php --format=text --host=test 2&gt;&amp;1
UpgradeConfig.up.test.php
UNIT: Upgrade Classes: lib/OA/Upgrade/UpgradeConfig.up.test.php
1) New config items have NOT been added to working test.conf.php at [/var/www/html/revive-adserver-badLogin/lib/OA/Upgrade/tests/unit/UpgradeConfig.up.test.php line 283]
        in test_checkForConfigAdditions
        in Test_OA_Upgrade_Config
        in /var/www/html/revive-adserver-badLogin/lib/OA/Upgrade/tests/unit/UpgradeConfig.up.test.php
FAILURES!!!
Test cases run: 1/1, Passes: 94, Failures: 1, Exceptions: 0</fail>
              <time>62.383148908615</time>
            </test>
          </case>
...
```
Corrected for the UpgradeConfig error as follows:
```
nano var/test.conf.php;#add badLoginLogPath
```
Run the test individually:
```
sudo -u www-data /usr/bin/php run.php --type=unit --level=file --layer=up --folder=lib/OA/Upgrade --file=UpgradeConfig.up.test.php --format=text --host=test
```
Gave this result:
```
UNIT: Upgrade Classes: lib/OA/Upgrade/UpgradeConfig.up.test.php
OK
Test cases run: 1/1, Passes: 95, Failures: 0, Exceptions: 0
```

I am using a version of MariaDB (15.1) where the utf8 charset is an alias of utf8mb3 as explained here: https://mariadb.com/kb/en/unicode/
This is the reason for the charset related failure.

Here are the unit and integration test result files:
[revive_badLogin_test_results.zip](https://github.com/revive-adserver/revive-adserver/files/9277631/revive_badLogin_test_results.zip)

@mbeccati and @erikgeurts , is there any way I could ease in the evaluation of this PR?
Is there a specific area where an improvement would be necessary?

**Comment by mbeccati** [comment]
Thanks @lcuis, I will have a look in the next few weeks and follow up.

**Comment by mbeccati** [comment]
@lcuis Thanks again and sorry for the huge delay.

**Comment by lcuis** [comment]
No worries @mbeccati and thanks a lot for the merge!

**Pull request merged**
