### PR TITLE
Force GeoLocation to be recomputed on IP or MMDB update

### PR DESCRIPTION
**Pull request by mringhausen**
Because GEO cookies are set for 1 year, in case of IP change or GeoIP2 database update, user location can be wrong particularly in case of roaming (with a mobile phone or laptop browser).

This pull request proposes to force recalculation of user location if his IP or MMDB file has changed by including both in the cookie.
These changes have been successfully tested on our production server.

### CODE REVIEW

**Comment by mbeccati** [comment]
Thanks for the PR, however the cookie is a session cookie, which expires when closing the browser. I don't think we really need recalculations.

**Comment by mringhausen** [comment]
Who closes their browser today? Particularly on your laptop (which you put on standby) or your smart-phone (>70% internet surfing)!

**Comment by erikgeurts** [comment]
Since it's a session cookie, it also expires after the defined session length in Revive Adserver, which I believe is 20 minutes.

In addition, storing a user's IP address in the cookie is almost certainly in violation of privacy regulations such as GDPR.

**Comment by erikgeurts** [comment]
> Since it's a session cookie, it also expires after the defined session length in Revive Adserver, which I believe is 20 minutes.

I need to correct myself, the geo cookie does not expire, I mixed it up with the session cookie.

**Comment by mringhausen** [comment]
@erikgeurts : right GEO expires after 1 year. That's why I propose this PR.
For RGPD compliance: IP is anonymous (X.X.X.0) but I can hash with MD5 too if needed.

**Comment by erikgeurts** [comment]
I guess you mean GDPR?

I still don't think storing an IP address makes sense. If you really think this is useful, I would suggest a timestamp that markes when the location value was last stored, and then to invalidate it based on expired time.

**Comment by mbeccati** [comment]
Yes, I don't think we need to overcomplicate here. We could simply change the cookie to be persistent with an expiry time of 1h or 30m.

**Comment by mringhausen** [comment]
@mbeccati : not so easy to change that ! 
www/delivery/* have a method called: _getTimeYearFromNow

**Comment by mringhausen** [comment]
> I guess you mean GDPR?
> 
> I still don't think storing an IP address makes sense. If you really think this is useful, I would suggest a timestamp that markes when the location value was last stored, and then to invalidate it based on expired time.

Sorry RGPD is GDPR in french :/
A timestamp can be stored intead anonymous IP but less "real time" that IP or any IP hash. My point is to be very accurate for roaming needs.

**Comment by mbeccati** [comment]
Thanks again for the contribution. Even if it wasn't merged, I think it has led to a viable improvement.

If you wish to try #1508 you can download the plugin: https://github.com/revive-adserver/revive-adserver/raw/898f4adefc4b4dc3c38e5d6f2ee249b7f06d8521/etc/plugins/reviveMaxMindGeoIP2.zip

**Pull request closed without merging**
