### PR TITLE
Fix broken Korean translations

### LINKED ISSUE #649: Korean translation was broken
Korean text in files of [Korean](https://github.com/revive-adserver/revive-adserver/tree/master/lib/max/language/ko) were borken :(

It looks like hex code such as `캠페�?�`.

The original text is `캠페인`.

### PR DESCRIPTION
**Pull request by jeyraof**
Fix #649

### CODE REVIEW

**Comment by erikgeurts** [comment]
Please use the translation project we've opened for Revive Adserver at http://translations.revive-adserver.com, in this case http://translations.revive-adserver.com/project/revive-adserver/ko

**Comment by jeyraof** [comment]
@erikgeurts Can you approve crowdin join request?

**Comment by erikgeurts** [comment]
It has just been approved. Have fun!

**Comment by jeyraof** [comment]
is there any way to upload fixed file content to crowdin?
I have to fix one more time from first of all..

**Comment by erikgeurts** [comment]
I'm not aware of any way to do this. I'm sorry. More information about the translation project can be found in our blog at https://www.revive-adserver.com/blog/translations-for-revive-adserver/

**Comment by jeyraof** [comment]
yep.. I got it. thanks.

**Pull request closed without merging**
