### PR TITLE
Fix PEAR Date bug and allow REST API to set campaign expire_time to never expire

### PR DESCRIPTION
**Pull request by mvdklip**
While working on a request for adding the ability to set the expire time of a campaing to never expire I found two components in the main ad server which prohibited this. While examining the web ui I saw that it is passing a NULL to set the expire time to never expire, so I set out to make the REST API do the same. Internally this NULL is converted into a PEAR Date which then becomes an (invalid) date in the year zero. However due to a bug in PEAR Date the date got mangled during conversion to UTC. Fixing that is one part of this PR. The other part is handling the year zero date inside the campaign dll and converting it back into a proper SQL NULL.

### CODE REVIEW

**Comment by Quix0r** [comment]
Na, changing external libraries (PEAR is not from revive) make it later maybe impossible to update the lib (generally said). So maybe report this change upstream (to PEAR, not here).

**Comment by mvdklip** [comment]
Unless the package is not maintained anymore and revive chooses to still
include it?

**Comment by Quix0r** [comment]
When it has been abandoned, go the usual way of forking it and then fix it there. If you only fix it here, the fix won't likely spread and remains unfixed in many other places. If they find it there, too. I think they will be glad someone came up with a fixed version.

Or also abandon it here, too and switch to a successor project (for PEAR I currently don't know).

**Comment by mbeccati** [comment]
FYI, the PEAR packages included with Revive have been forks since a long time as some of our patches and fixes hadn't been accepted upstream.

**Comment by mbeccati** [comment]
I've reviewed the PR and after lots of thinking, I don't feel this is the right approach: An invalid date is a poor substitute for a proper NULL value. XML-RPC cannot represent the NULL type, but there is an [extension ](https://web.archive.org/web/20050911054235/http://ontosys.com/xml-rpc/extensions.php) for it that adds **<nil/>**. Going from memory, the PEAR client/server library we use doesn't support it, but ultimately it should not be extremely hard to go that route.

**Comment by chasebolt** [comment]
is there any plans in the works for fixing this? this is a long lived bug which affects the REST API.

**Comment by erikgeurts** [comment]
Revive Adserver is capable of setting the end date of a campaign to 'don't expire' by setting the campaign's end date to a 'null' value in the 'expire_time' column of the rv_campaigns table. This is possible because the core software doesn't make use of the API.

As explained by @mbeccati in his earlier comment above, this issue originates from the fact that the XML-RPC specifications do not have any way to represent a NULL value. This is unfortunate, but not something we can easily fix. I see Matteo's point that passing an invalid date is not a good alternative for passing a real 'null' value. That still leaves us with the question of how to handle this from an API.

Developers using the XML-RPC API or the [REST API](https://www.reviveadserverrestapi.com/) (full disclosure: the latter is a commercial, third party product sold by my company) and in need of a way to get around this issue, could consider implementing the work-around provided by @mvdklip in his [commits](https://github.com/revive-adserver/revive-adserver/pull/768/commits) from October 12, 2016. Even though it may not be the most pure approach, it does work and will enable developers to proceed.

**Pull request closed without merging**
