### PR TITLE
Alternative solution for #1507

### PR DESCRIPTION
**Pull request by mbeccati**

### CODE REVIEW

**Comment by mbeccati** [comment]
@mringhausen What do you think about this?

**Comment by erikgeurts** [comment]
> @mringhausen What do you think about this?

I like this approach, although I wonder if 30 minutes for auto-expiry isn't too short. It might also be smart to make the time configurable in the config file, so that it is easier to tweak it without having to go into the code.

**Comment by mbeccati** [comment]
@erikgeurts I'm conflicted beteween removing the cookie altogether or this solution. That's why I didn't bother adding a configuration entry. The overhead of geoip lookup is small, even doing it every few minutes should be ok.

My thought process was something like "30m should be plenty for an average visit to a website that is serving ads from the Revive instance and if someone's on the move it's ok to recalculate geo when visiting multiple times during the day".

**Comment by erikgeurts** [comment]
I understand and agree with your reasoning. In fact, once 3p cookies get blocked, it would lose its function for many installations anyway. Removing the cooking now just makes it OLCTWA (one less cookie to worry about).

**Comment by mbeccati** [comment]
I think I'll go ahead and merge this. We might end up removing the cookie before the next release, but for now this should suffice.

**Comment by mringhausen** [comment]
So complexity grow up. My approach in PR #1507 did'nt needs of settings, just changes auto-detection.

**Comment by mbeccati** [comment]
@mringhausen I don't think complexity has increased.

Every 30m geoip will be refreshed without need to check for file modification time or IP address changes, which was not guaranteed to be stable during a session anyway.

**Pull request merged**
