### PR TITLE
PHP 7 is terminated by a timeout when comparing dates;

### PR DESCRIPTION
**Pull request by dkulyk**
Daily statistics terminated by timeout on PHP7:
```
... other calls
convertTZ() www/lib/pear/Date.php:736
compare() www/lib/pear/Date.php:762
before() www/lib/OA/Admin/Statistics/History.php:308
getDatesArray() www/lib/OA/Admin/Statistics/Delivery/CommonHistory.php:264
getHistory() www/lib/OA/Admin/Statistics/Delivery/CommonHistory.php:142
prepare() www/lib/OA/Admin/Statistics/Delivery/Controller/BannerHistory.php:124
start() www/www/admin/stats.php:163
```
OA_Admin_Statistics_History::getDatesArray rewritten using DateTime. 
It is also necessary to check the dates of the output format.

### CODE REVIEW

**Comment by mbeccati** [comment]
The whole system still uses PEAR_Date. Moving just a single part to \DateTime doesn't seem consistent. Maybe we can fix the offending part in PEAR_Date?

**Comment by dkulyk** [comment]
I do not think that it is necessary to use an outdated code, for which there is a standard solution

**Comment by mbeccati** [comment]
I know, I'd love to get everything moved to \DateTime, not just a single function. Could you please share any info on how to replicate (i.e. start / end and your timezone)?

**Comment by dkulyk** [comment]
Daily statistics between 22 February 2016 and 28 February 2016, Europe/Kiev

**Comment by mbeccati** [comment]
Just tried to replicate with php 7.0.4, no luck. All is working fine.

**Comment by dkulyk** [comment]
```
PHP 7.0.3-pl0-gentoo (cli) (built: Feb 17 2016 13:13:03) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```
```
Configure Command =>  './configure'  '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--prefix=/usr/lib64/php7.0' '--mandir=/usr/lib64/php7.0/man' '--infodir=/usr/lib64/php7.0/info' '--libdir=/usr/lib64/php7.0/lib' '--with-libdir=lib64' '--localstatedir=/var' '--without-pear' '--disable-maintainer-zts' '--disable-bcmath' '--with-bz2=/usr' '--disable-calendar' '--enable-ctype' '--with-curl=/usr' '--enable-dom' '--without-enchant' '--enable-exif' '--enable-fileinfo' '--enable-filter' '--enable-ftp' '--with-gettext=/usr' '--without-gmp' '--enable-hash' '--without-mhash' '--with-iconv' '--enable-intl' '--disable-ipv6' '--enable-json' '--with-kerberos=/usr' '--enable-libxml' '--with-libxml-dir=/usr' '--enable-mbstring' '--with-mcrypt=/usr' '--with-onig=/usr' '--with-openssl=/usr' '--with-openssl-dir=/usr' '--disable-pcntl' '--enable-phar' '--enable-pdo' '--enable-opcache' '--without-pgsql' '--enable-posix' '--without-pspell' '--without-recode' '--enable-simplexml' '--disable-shmop' '--without-snmp' '--enable-soap' '--enable-sockets' '--without-sqlite3' '--disable-sysvmsg' '--disable-sysvsem' '--disable-sysvshm' '--without-fpm-systemd' '--with-tidy=/usr' '--enable-tokenizer' '--disable-wddx' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--without-xmlrpc' '--with-xsl=/usr' '--enable-zip' '--with-zlib=/usr' '--disable-debug' '--without-cdb' '--without-db4' '--disable-flatfile' '--without-gdbm' '--disable-inifile' '--without-qdbm' '--with-freetype-dir=/usr' '--disable-gd-jis-conv' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--without-xpm-dir' '--with-gd' '--with-imap=/usr' '--with-imap-ssl=/usr' '--without-interbase' '--with-mysqli=mysqlnd' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--without-unixODBC' '--without-iodbc' '--without-oci8' '--with-pdo-mysql=mysqlnd' '--without-pdo-pgsql' '--without-pdo-sqlite' '--without-pdo-firebird' '--without-pdo-odbc' '--without-pdo-oci' '--with-readline=/usr' '--without-libedit' '--without-mm' '--with-pic' '--with-pcre-regex=/usr' '--with-pcre-dir=/usr' '--with-config-file-path=/etc/php/cli-php7.0' '--with-config-file-scan-dir=/etc/php/cli-php7.0/ext-active' '--disable-embed' '--enable-cli' '--disable-cgi' '--disable-fpm' '--without-apxs2' '--disable-phpdbg' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-O2 '-pipe' '-march=native'' 'LDFLAGS=-Wl,-O1 '-Wl,--as-needed'' 'CPPFLAGS=' 'CXXFLAGS=-O2 '-pipe' '-march=native''
```

**Comment by dkulyk** [comment]
I located the bug. Issue #680 Pull #681

**Comment by mbeccati** [comment]
Nice catch, thanks!

**Comment by mbeccati** [comment]
@dkulyk thanks again. Closing this PR.

**Pull request closed without merging**
