### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### revive-adserver/revive-adserver now has a Chat Room on Gitter

@mbeccati has just created a chat room. You can visit it here: [https://gitter.im/revive-adserver/revive-adserver](https://gitter.im/revive-adserver/revive-adserver?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/revive-adserver/revive-adserver?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by erikgeurts** [comment]
@mbeccati Why would we need this?

**Comment by mbeccati** [comment]
@erikgeurts it's a tool the cool guys use to discuss pull requests in real time. I found it yesterday and I thought that having this PR created would remind me about it in future - should we need something like it.

**Comment by andrewatfornax** [comment]
@mbeccati - I find I never really go to Gitter. Should we consider closing the account and reverting this PR?

**Comment by mbeccati** [comment]
@andrewatfornax Sounds like a good idea

**Pull request merged**
