### PR TITLE
fix export to excel link on stats pages

### PR DESCRIPTION
**Pull request by sryabov**

### CODE REVIEW

**Comment by mbeccati** [comment]
Could you please provide a description on how to replicate the issue?

**Comment by sryabov** [comment]
Link "Export to Excel" on all "stats" pages does not contain current selection and as result downloaded file has info on all banner zones for all time.

**Comment by sryabov** [comment]
And variable "aGraphData[queryString]" does not exsists in template.

**Comment by mbeccati** [comment]
@sryabov thanks. Is this related to #371 ?

**Comment by sryabov** [comment]
@mbeccati yes, relates

**Comment by mbeccati** [comment]
Applied. Thanks!

**Pull request closed without merging**
